name: Build
on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'debug level'
        required: true
        default: 'info'
        type: choice
        options:
        - debug
        - info
jobs:
  build:
    name: 'build container'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Run feedme
        run: uv run ./feedme.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tmp.html
          path: ./tmp.html
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tmp.html
      - name: Copy artifact to repository
        run: |
          mv tmp.html index.html
          git config user.name "Douglas Land"
          git config user.email dsl@looprock.com
          git add index.html
          git commit -m "update index.html"
          git push
